# Generated by Django 3.1.7 on 2021-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_register_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_volunteer',
            field=models.BooleanField(default=True),
        ),
    ]
