# Generated by Django 3.1.7 on 2021-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volunteer_status',
            field=models.BooleanField(default=False),
        ),
    ]
