# Generated by Django 3.1.7 on 2021-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_volunteer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='volunteer_status',
        ),
        migrations.AddField(
            model_name='taker',
            name='volunteer_status',
            field=models.BooleanField(default=False),
        ),
    ]
