# Generated by Django 3.1.7 on 2021-07-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210715_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='taker',
            name='last_name',
        ),
    ]
